# Generated by Django 4.2.2 on 2024-06-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='время попытки')),
                ('success', models.BooleanField(default=False, verbose_name='успешно')),
                ('response', models.TextField(verbose_name='ответ сервера')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='e-mail')),
                ('fio', models.CharField(max_length=128, verbose_name='ф.и.о.')),
                ('info', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='тема')),
                ('body', models.TextField(verbose_name='содержимое')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщений',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('start', models.DateTimeField(verbose_name='время начала')),
                ('finish', models.DateTimeField(verbose_name='время окончания')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(3, 'monthly'), (1, 'dayly'), (2, 'weekly')], default=1, verbose_name='периодичность')),
                ('status', models.PositiveSmallIntegerField(choices=[(3, 'completed'), (2, 'launched'), (1, 'created')], default=1, verbose_name='статус')),
                ('clients', models.ManyToManyField(to='mailer.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.message')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.client', verbose_name='клиент')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
            },
        ),
    ]
