# Generated by Django 4.2.2 on 2024-06-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_attempt_newsletter_alter_client_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='finish',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'monthly'), (2, 'weekly'), (1, 'dayly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'completed'), (1, 'created'), (2, 'launched')], default=1, verbose_name='статус'),
        ),
    ]
