# Generated by Django 4.2.2 on 2024-06-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_remove_newsletter_finish_alter_newsletter_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='mailer.client', verbose_name='получатели'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(2, 'weekly'), (1, 'dayly'), (3, 'monthly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.message', verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (3, 'completed'), (2, 'launched')], default=1, verbose_name='статус'),
        ),
    ]
