# Generated by Django 4.2.2 on 2024-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_alter_newsletter_frequency_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(2, 'weekly'), (1, 'dayly'), (3, 'monthly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'completed'), (1, 'created'), (2, 'launched')], default=1, verbose_name='статус'),
        ),
    ]
