# Generated by Django 4.2.2 on 2024-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_alter_newsletter_frequency_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'completed'), (2, 'launched'), (1, 'created')], default=1, verbose_name='статус'),
        ),
    ]
