# Generated by Django 4.2.2 on 2024-06-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('set_block', 'Can enable / disable newsletter')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='заблокировано'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'monthly'), (2, 'weekly'), (1, 'dayly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'launched'), (1, 'created'), (3, 'completed')], default=1, verbose_name='статус'),
        ),
    ]
