# Generated by Django 4.2.2 on 2024-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_alter_newsletter_options_newsletter_is_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'dayly'), (3, 'monthly'), (2, 'weekly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'launched'), (3, 'completed'), (1, 'created')], default=1, verbose_name='статус'),
        ),
    ]
