# Generated by Django 4.2.2 on 2024-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0014_alter_newsletter_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'dayly'), (2, 'weekly'), (3, 'monthly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (3, 'completed'), (2, 'launched')], default=1, verbose_name='статус'),
        ),
    ]
