# Generated by Django 4.2.2 on 2024-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_alter_newsletter_options_alter_newsletter_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(2, 'weekly'), (1, 'dayly'), (3, 'monthly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'completed'), (2, 'launched'), (1, 'created')], default=1, verbose_name='статус'),
        ),
    ]
