# Generated by Django 4.2.2 on 2024-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0019_alter_newsletter_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'dayly'), (2, 'weekly'), (3, 'monthly')], default=1, verbose_name='периодичность'),
        ),
    ]
