# Generated by Django 4.2.2 on 2024-07-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0020_alter_newsletter_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(3, 'monthly'), (2, 'weekly'), (1, 'dayly')], default=1, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'completed'), (1, 'created'), (2, 'launched')], default=1, verbose_name='статус'),
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
