# Generated by Django 4.2.2 on 2024-06-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_publshed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publshed_at',
            new_name='published_at',
        ),
    ]
